#!/bin/env ruby
# encoding: utf-8

class AddInitialCidade < ActiveRecord::Migration
  def up
    Cidade.create!(:estado_id => 15, :chave => '4848', :nome => 'Agua Branca');
    Cidade.create!(:estado_id => 15, :chave => '4849', :nome => 'Aguiar');
    Cidade.create!(:estado_id => 15, :chave => '4850', :nome => 'Alagoa Grande');
    Cidade.create!(:estado_id => 15, :chave => '4851', :nome => 'Alagoa Nova');
    Cidade.create!(:estado_id => 15, :chave => '4852', :nome => 'Alagoinha');
    Cidade.create!(:estado_id => 15, :chave => '4853', :nome => 'Alcantil');
    Cidade.create!(:estado_id => 15, :chave => '4854', :nome => 'Algodão de Jandaíra');
    Cidade.create!(:estado_id => 15, :chave => '4855', :nome => 'Alhandra');
    Cidade.create!(:estado_id => 15, :chave => '4856', :nome => 'Amparo');
    Cidade.create!(:estado_id => 15, :chave => '4857', :nome => 'Aparecida');
    Cidade.create!(:estado_id => 15, :chave => '4858', :nome => 'Araçagi');
    Cidade.create!(:estado_id => 15, :chave => '4859', :nome => 'Arara');
    Cidade.create!(:estado_id => 15, :chave => '4860', :nome => 'Araruna');
    Cidade.create!(:estado_id => 15, :chave => '4861', :nome => 'Areia');
    Cidade.create!(:estado_id => 15, :chave => '4862', :nome => 'Areia de Baraúnas');
    Cidade.create!(:estado_id => 15, :chave => '4863', :nome => 'Areial');
    Cidade.create!(:estado_id => 15, :chave => '4864', :nome => 'Areias (Uiraúna)');
    Cidade.create!(:estado_id => 15, :chave => '4865', :nome => 'Aroeiras');
    Cidade.create!(:estado_id => 15, :chave => '4866', :nome => 'Riachão do Bacamarte');
    Cidade.create!(:estado_id => 15, :chave => '4867', :nome => 'Assunção');
    Cidade.create!(:estado_id => 15, :chave => '4868', :nome => 'Baía da Traição');
    Cidade.create!(:estado_id => 15, :chave => '4869', :nome => 'Balanços (Cachoeira dos Índios)');
    Cidade.create!(:estado_id => 15, :chave => '4870', :nome => 'Bananeiras');
    Cidade.create!(:estado_id => 15, :chave => '4871', :nome => 'Baraúna');
    Cidade.create!(:estado_id => 15, :chave => '4872', :nome => 'Barra de Santa Rosa');
    Cidade.create!(:estado_id => 15, :chave => '4873', :nome => 'Barra de Santana');
    Cidade.create!(:estado_id => 15, :chave => '4874', :nome => 'Barra de São Miguel');
    Cidade.create!(:estado_id => 15, :chave => '4875', :nome => 'Barra do Camaratuba (Mataraca)');
    Cidade.create!(:estado_id => 15, :chave => '4876', :nome => 'Bayeux');
    Cidade.create!(:estado_id => 15, :chave => '4877', :nome => 'Belém');
    Cidade.create!(:estado_id => 15, :chave => '4878', :nome => 'Belém do Brejo do Cruz');
    Cidade.create!(:estado_id => 15, :chave => '4879', :nome => 'Bernardino Batista');
    Cidade.create!(:estado_id => 15, :chave => '4880', :nome => 'Boa Ventura');
    Cidade.create!(:estado_id => 15, :chave => '4881', :nome => 'Boa Vista');
    Cidade.create!(:estado_id => 15, :chave => '4882', :nome => 'Bom Jesus');
    Cidade.create!(:estado_id => 15, :chave => '4883', :nome => 'Bom Sucesso');
    Cidade.create!(:estado_id => 15, :chave => '4884', :nome => 'Bom Sucesso (Soledade)');
    Cidade.create!(:estado_id => 15, :chave => '4885', :nome => 'Bonito de Santa Fé');
    Cidade.create!(:estado_id => 15, :chave => '4886', :nome => 'Boqueirão');
    Cidade.create!(:estado_id => 15, :chave => '4887', :nome => 'Borborema');
    Cidade.create!(:estado_id => 15, :chave => '4888', :nome => 'Brejo do Cruz');
    Cidade.create!(:estado_id => 15, :chave => '4889', :nome => 'Brejo dos Santos');
    Cidade.create!(:estado_id => 15, :chave => '4890', :nome => 'Caaporã');
    Cidade.create!(:estado_id => 15, :chave => '4891', :nome => 'Cabaceiras');
    Cidade.create!(:estado_id => 15, :chave => '4892', :nome => 'Cabedelo');
    Cidade.create!(:estado_id => 15, :chave => '4893', :nome => 'Cachoeira (Guarabira)');
    Cidade.create!(:estado_id => 15, :chave => '4894', :nome => 'Cachoeira dos Índios');
    Cidade.create!(:estado_id => 15, :chave => '4895', :nome => 'Cachoeirinha (Ibiara)');
    Cidade.create!(:estado_id => 15, :chave => '4896', :nome => 'Cacimba de Areia');
    Cidade.create!(:estado_id => 15, :chave => '4897', :nome => 'Cacimba de Dentro');
    Cidade.create!(:estado_id => 15, :chave => '4898', :nome => 'Cacimbas');
    Cidade.create!(:estado_id => 15, :chave => '4899', :nome => 'Caiçara');
    Cidade.create!(:estado_id => 15, :chave => '4900', :nome => 'Cajazeiras');
    Cidade.create!(:estado_id => 15, :chave => '4901', :nome => 'Cajazeirinhas');
    Cidade.create!(:estado_id => 15, :chave => '4902', :nome => 'Caldas Brandão');
    Cidade.create!(:estado_id => 15, :chave => '4903', :nome => 'Camalaú');
    Cidade.create!(:estado_id => 15, :chave => '4904', :nome => 'Campina Grande');
    Cidade.create!(:estado_id => 15, :chave => '4905', :nome => 'Campo Alegre (Sousa)');
    Cidade.create!(:estado_id => 15, :chave => '4906', :nome => 'Campo Grande (Itabaiana)');
    Cidade.create!(:estado_id => 15, :chave => '4907', :nome => 'Camurupim (Rio Tinto)');
    Cidade.create!(:estado_id => 15, :chave => '4908', :nome => 'Capim');
    Cidade.create!(:estado_id => 15, :chave => '4909', :nome => 'Caraúbas');
    Cidade.create!(:estado_id => 15, :chave => '4910', :nome => 'Cardoso (Conceição)');
    Cidade.create!(:estado_id => 15, :chave => '4911', :nome => 'Carrapateira');
    Cidade.create!(:estado_id => 15, :chave => '4912', :nome => 'Casinha do Homem (Santa Cruz)');
    Cidade.create!(:estado_id => 15, :chave => '4913', :nome => 'Casserengue');
    Cidade.create!(:estado_id => 15, :chave => '4914', :nome => 'Catingueira');
    Cidade.create!(:estado_id => 15, :chave => '4915', :nome => 'Catolé (Campina Grande)');
    Cidade.create!(:estado_id => 15, :chave => '4916', :nome => 'Catolé do Rocha');
    Cidade.create!(:estado_id => 15, :chave => '4917', :nome => 'Caturité');
    Cidade.create!(:estado_id => 15, :chave => '4918', :nome => 'Cepilho (Areia)');
    Cidade.create!(:estado_id => 15, :chave => '4919', :nome => 'Conceição');
    Cidade.create!(:estado_id => 15, :chave => '4920', :nome => 'Condado');
    Cidade.create!(:estado_id => 15, :chave => '4921', :nome => 'Conde');
    Cidade.create!(:estado_id => 15, :chave => '4922', :nome => 'Congo');
    Cidade.create!(:estado_id => 15, :chave => '4923', :nome => 'Coremas');
    Cidade.create!(:estado_id => 15, :chave => '4924', :nome => 'Coronel Maia (Catolé do Rocha)');
    Cidade.create!(:estado_id => 15, :chave => '4925', :nome => 'Coxixola');
    Cidade.create!(:estado_id => 15, :chave => '4926', :nome => 'Cruz do Espírito Santo');
    Cidade.create!(:estado_id => 15, :chave => '4927', :nome => 'Cubati');
    Cidade.create!(:estado_id => 15, :chave => '4928', :nome => 'Cuité');
    Cidade.create!(:estado_id => 15, :chave => '4929', :nome => 'Cuité de Mamanguape');
    Cidade.create!(:estado_id => 15, :chave => '4930', :nome => 'Cuitegi');
    Cidade.create!(:estado_id => 15, :chave => '4931', :nome => 'Cupissura (Caaporã)');
    Cidade.create!(:estado_id => 15, :chave => '4932', :nome => 'Curral de Cima');
    Cidade.create!(:estado_id => 15, :chave => '4933', :nome => 'Curral Velho');
    Cidade.create!(:estado_id => 15, :chave => '4934', :nome => 'Damião');
    Cidade.create!(:estado_id => 15, :chave => '4935', :nome => 'Desterro');
    Cidade.create!(:estado_id => 15, :chave => '4936', :nome => 'Diamante');
    Cidade.create!(:estado_id => 15, :chave => '4937', :nome => 'Dona Inís');
    Cidade.create!(:estado_id => 15, :chave => '4938', :nome => 'Duas Estradas');
    Cidade.create!(:estado_id => 15, :chave => '4939', :nome => 'Emas');
    Cidade.create!(:estado_id => 15, :chave => '4940', :nome => 'Engenheiro ¡vidos (Cajazeiras)');
    Cidade.create!(:estado_id => 15, :chave => '4941', :nome => 'Esperança');
    Cidade.create!(:estado_id => 15, :chave => '4942', :nome => 'Fagundes');
    Cidade.create!(:estado_id => 15, :chave => '4943', :nome => 'Fátima (Cachoeira dos Índios)');
    Cidade.create!(:estado_id => 15, :chave => '4944', :nome => 'Fazenda Nova (Uiraúna)');
    Cidade.create!(:estado_id => 15, :chave => '4945', :nome => 'Forte Velho (Santa Rita)');
    Cidade.create!(:estado_id => 15, :chave => '4946', :nome => 'Frei Martinho');
    Cidade.create!(:estado_id => 15, :chave => '4947', :nome => 'Gado Bravo');
    Cidade.create!(:estado_id => 15, :chave => '4948', :nome => 'Galante (Campina Grande)');
    Cidade.create!(:estado_id => 15, :chave => '4949', :nome => 'Guarabira');
    Cidade.create!(:estado_id => 15, :chave => '4950', :nome => 'Guarita (Itabaiana)');
    Cidade.create!(:estado_id => 15, :chave => '4951', :nome => 'Gurinhém');
    Cidade.create!(:estado_id => 15, :chave => '4952', :nome => 'Gurjão');
    Cidade.create!(:estado_id => 15, :chave => '4953', :nome => 'Ibiara');
    Cidade.create!(:estado_id => 15, :chave => '4954', :nome => 'Igaracy');
    Cidade.create!(:estado_id => 15, :chave => '4955', :nome => 'Imaculada');
    Cidade.create!(:estado_id => 15, :chave => '4956', :nome => 'Ingá');
    Cidade.create!(:estado_id => 15, :chave => '4957', :nome => 'Itabaiana');
    Cidade.create!(:estado_id => 15, :chave => '4958', :nome => 'Itajubatiba (Catingueira)');
    Cidade.create!(:estado_id => 15, :chave => '4959', :nome => 'Itaporanga');
    Cidade.create!(:estado_id => 15, :chave => '4960', :nome => 'Itapororoca');
    Cidade.create!(:estado_id => 15, :chave => '4961', :nome => 'Itatuba');
    Cidade.create!(:estado_id => 15, :chave => '4962', :nome => 'Jacaraú');
    Cidade.create!(:estado_id => 15, :chave => '4963', :nome => 'Jericó');
    Cidade.create!(:estado_id => 15, :chave => '4964', :nome => 'João Pessoa');
    Cidade.create!(:estado_id => 15, :chave => '4965', :nome => 'Juarez Távora');
    Cidade.create!(:estado_id => 15, :chave => '4966', :nome => 'Juazeirinho');
    Cidade.create!(:estado_id => 15, :chave => '4967', :nome => 'Junco do Seridó');
    Cidade.create!(:estado_id => 15, :chave => '4968', :nome => 'Juripiranga');
    Cidade.create!(:estado_id => 15, :chave => '4969', :nome => 'Juru');
    Cidade.create!(:estado_id => 15, :chave => '4970', :nome => 'Lagoa');
    Cidade.create!(:estado_id => 15, :chave => '4971', :nome => 'Lagoa de Dentro');
    Cidade.create!(:estado_id => 15, :chave => '4972', :nome => 'Lagoa de Dentro (Campina Grande)');
    Cidade.create!(:estado_id => 15, :chave => '4973', :nome => 'Lagoa Seca');
    Cidade.create!(:estado_id => 15, :chave => '4974', :nome => 'Lastro');
    Cidade.create!(:estado_id => 15, :chave => '4975', :nome => 'Lerolândia (Santa Rita)');
    Cidade.create!(:estado_id => 15, :chave => '4976', :nome => 'Livramento');
    Cidade.create!(:estado_id => 15, :chave => '4977', :nome => 'Logradouro');
    Cidade.create!(:estado_id => 15, :chave => '4978', :nome => 'Lucena');
    Cidade.create!(:estado_id => 15, :chave => '4979', :nome => 'Mãe D\'água');
    Cidade.create!(:estado_id => 15, :chave => '4980', :nome => 'Maia (Bananeiras)');
    Cidade.create!(:estado_id => 15, :chave => '4981', :nome => 'Malta');
    Cidade.create!(:estado_id => 15, :chave => '4982', :nome => 'Mamanguape');
    Cidade.create!(:estado_id => 15, :chave => '4983', :nome => 'Manaíra');
    Cidade.create!(:estado_id => 15, :chave => '4984', :nome => 'Marcação');
    Cidade.create!(:estado_id => 15, :chave => '4985', :nome => 'Mari');
    Cidade.create!(:estado_id => 15, :chave => '4986', :nome => 'Marizópolis');
    Cidade.create!(:estado_id => 15, :chave => '4987', :nome => 'Massaranduba');
    Cidade.create!(:estado_id => 15, :chave => '4988', :nome => 'Mata Limpa (Areia)');
    Cidade.create!(:estado_id => 15, :chave => '4989', :nome => 'Mata Virgem (Umbuzeiro)');
    Cidade.create!(:estado_id => 15, :chave => '4990', :nome => 'Mataraca');
    Cidade.create!(:estado_id => 15, :chave => '4991', :nome => 'Matinhas');
    Cidade.create!(:estado_id => 15, :chave => '4992', :nome => 'Mato Grosso');
    Cidade.create!(:estado_id => 15, :chave => '4993', :nome => 'Maturéia');
    Cidade.create!(:estado_id => 15, :chave => '4994', :nome => 'Melo (Cuité)');
    Cidade.create!(:estado_id => 15, :chave => '4995', :nome => 'Mogeiro');
    Cidade.create!(:estado_id => 15, :chave => '4996', :nome => 'Montadas');
    Cidade.create!(:estado_id => 15, :chave => '4997', :nome => 'Monte Horebe');
    Cidade.create!(:estado_id => 15, :chave => '4998', :nome => 'Monteiro');
    Cidade.create!(:estado_id => 15, :chave => '4999', :nome => 'Montevidéu (Conceição)');
    Cidade.create!(:estado_id => 15, :chave => '5000', :nome => 'Mulungu');
    Cidade.create!(:estado_id => 15, :chave => '5001', :nome => 'Muquém (Areia)');
    Cidade.create!(:estado_id => 15, :chave => '5002', :nome => 'Natuba');
    Cidade.create!(:estado_id => 15, :chave => '5003', :nome => 'Nazaré (Pocinhos)');
    Cidade.create!(:estado_id => 15, :chave => '5004', :nome => 'Nazarezinho');
    Cidade.create!(:estado_id => 15, :chave => '5005', :nome => 'Nossa Senhora do Livramento (Santa Rita)');
    Cidade.create!(:estado_id => 15, :chave => '5006', :nome => 'Nova Floresta');
    Cidade.create!(:estado_id => 15, :chave => '5007', :nome => 'Nova Olinda');
    Cidade.create!(:estado_id => 15, :chave => '5008', :nome => 'Nova Palmeira');
    Cidade.create!(:estado_id => 15, :chave => '5009', :nome => 'Núcleo N 2 (Sousa)');
    Cidade.create!(:estado_id => 15, :chave => '5010', :nome => 'Núcleo N 3 (Sousa)');
    Cidade.create!(:estado_id => 15, :chave => '5011', :nome => 'Odilândia (Santa Rita)');
    Cidade.create!(:estado_id => 15, :chave => '5012', :nome => 'Olho D\'Água');
    Cidade.create!(:estado_id => 15, :chave => '5013', :nome => 'Olivedos');
    Cidade.create!(:estado_id => 15, :chave => '5014', :nome => 'Ouro Velho');
    Cidade.create!(:estado_id => 15, :chave => '5015', :nome => 'Parari');
    Cidade.create!(:estado_id => 15, :chave => '5016', :nome => 'Passagem');
    Cidade.create!(:estado_id => 15, :chave => '5017', :nome => 'Patos');
    Cidade.create!(:estado_id => 15, :chave => '5018', :nome => 'Paulista');
    Cidade.create!(:estado_id => 15, :chave => '5019', :nome => 'Pedra Branca');
    Cidade.create!(:estado_id => 15, :chave => '5020', :nome => 'Pedra Lavrada');
    Cidade.create!(:estado_id => 15, :chave => '5021', :nome => 'Pedras de Fogo');
    Cidade.create!(:estado_id => 15, :chave => '5022', :nome => 'Pedro Régis');
    Cidade.create!(:estado_id => 15, :chave => '5023', :nome => 'Pelo Sinal (Manaíra)');
    Cidade.create!(:estado_id => 15, :chave => '5024', :nome => 'Pereiros (Sousa)');
    Cidade.create!(:estado_id => 15, :chave => '5025', :nome => 'Piancó');
    Cidade.create!(:estado_id => 15, :chave => '5026', :nome => 'Picuí');
    Cidade.create!(:estado_id => 15, :chave => '5027', :nome => 'Pilar');
    Cidade.create!(:estado_id => 15, :chave => '5028', :nome => 'Pilões');
    Cidade.create!(:estado_id => 15, :chave => '5029', :nome => 'Pilõezinhos');
    Cidade.create!(:estado_id => 15, :chave => '5030', :nome => 'Pindurão (Camalaú)');
    Cidade.create!(:estado_id => 15, :chave => '5031', :nome => 'Pio X (Sumé)');
    Cidade.create!(:estado_id => 15, :chave => '5032', :nome => 'Pirauç (Natuba)');
    Cidade.create!(:estado_id => 15, :chave => '5033', :nome => 'Pirpirituba');
    Cidade.create!(:estado_id => 15, :chave => '5034', :nome => 'Pitanga de Estrada (Mamanguape)');
    Cidade.create!(:estado_id => 15, :chave => '5035', :nome => 'Pitimbu');
    Cidade.create!(:estado_id => 15, :chave => '5036', :nome => 'Pocinhos');
    Cidade.create!(:estado_id => 15, :chave => '5037', :nome => 'Poço Dantas');
    Cidade.create!(:estado_id => 15, :chave => '5038', :nome => 'Poço de José de Moura');
    Cidade.create!(:estado_id => 15, :chave => '5039', :nome => 'Pombal');
    Cidade.create!(:estado_id => 15, :chave => '5040', :nome => 'Porteirinha de Pedra (Campina Grande)');
    Cidade.create!(:estado_id => 15, :chave => '5041', :nome => 'Prata');
    Cidade.create!(:estado_id => 15, :chave => '5042', :nome => 'Princesa Isabel');
    Cidade.create!(:estado_id => 15, :chave => '5043', :nome => 'Puxinanã');
    Cidade.create!(:estado_id => 15, :chave => '5044', :nome => 'Queimadas');
    Cidade.create!(:estado_id => 15, :chave => '5045', :nome => 'Quixabç');
    Cidade.create!(:estado_id => 15, :chave => '5046', :nome => 'Quixadç (Uiraúna)');
    Cidade.create!(:estado_id => 15, :chave => '5047', :nome => 'Remígio');
    Cidade.create!(:estado_id => 15, :chave => '5048', :nome => 'Riachão');
    Cidade.create!(:estado_id => 15, :chave => '5049', :nome => 'Riachão do Poço');
    Cidade.create!(:estado_id => 15, :chave => '5050', :nome => 'Riacho de Santo Antõnio');
    Cidade.create!(:estado_id => 15, :chave => '5051', :nome => 'Riacho dos Cavalos');
    Cidade.create!(:estado_id => 15, :chave => '5052', :nome => 'Ribeira (Santa Rita)');
    Cidade.create!(:estado_id => 15, :chave => '5053', :nome => 'Rio Tinto');
    Cidade.create!(:estado_id => 15, :chave => '5054', :nome => 'Rua Nova (Belém)');
    Cidade.create!(:estado_id => 15, :chave => '5055', :nome => 'Salema (Rio Tinto)');
    Cidade.create!(:estado_id => 15, :chave => '5056', :nome => 'Salgadinho');
    Cidade.create!(:estado_id => 15, :chave => '5057', :nome => 'Salgado de São Félix');
    Cidade.create!(:estado_id => 15, :chave => '5058', :nome => 'Santa Cecília de Umbuzeiro');
    Cidade.create!(:estado_id => 15, :chave => '5059', :nome => 'Santa Cruz');
    Cidade.create!(:estado_id => 15, :chave => '5060', :nome => 'Santa Gertrudes (Patos)');
    Cidade.create!(:estado_id => 15, :chave => '5061', :nome => 'Santa Helena');
    Cidade.create!(:estado_id => 15, :chave => '5062', :nome => 'Santa Inís');
    Cidade.create!(:estado_id => 15, :chave => '5063', :nome => 'Santa Luzia');
    Cidade.create!(:estado_id => 15, :chave => '5064', :nome => 'Santa Luzia do Cariri (Serra Branca)');
    Cidade.create!(:estado_id => 15, :chave => '5065', :nome => 'Santa Maria (São João do Tigre)');
    Cidade.create!(:estado_id => 15, :chave => '5066', :nome => 'Santa Rita');
    Cidade.create!(:estado_id => 15, :chave => '5067', :nome => 'Santa Rita (Uiraúna)');
    Cidade.create!(:estado_id => 15, :chave => '5068', :nome => 'Santa Teresinha');
    Cidade.create!(:estado_id => 15, :chave => '5069', :nome => 'Santa Terezinha (Campina Grande)');
    Cidade.create!(:estado_id => 15, :chave => '5070', :nome => 'Santana de Mangueira');
    Cidade.create!(:estado_id => 15, :chave => '5071', :nome => 'Santana dos Garrotes');
    Cidade.create!(:estado_id => 15, :chave => '5072', :nome => 'Santarém');
    Cidade.create!(:estado_id => 15, :chave => '5073', :nome => 'Santo André');
    Cidade.create!(:estado_id => 15, :chave => '5074', :nome => 'São Bento');
    Cidade.create!(:estado_id => 15, :chave => '5075', :nome => 'São Bentinho');
    Cidade.create!(:estado_id => 15, :chave => '5076', :nome => 'São Domingos de Pombal');
    Cidade.create!(:estado_id => 15, :chave => '5077', :nome => 'São Domingos do Cariri');
    Cidade.create!(:estado_id => 15, :chave => '5078', :nome => 'São Francisco');
    Cidade.create!(:estado_id => 15, :chave => '5079', :nome => 'São Gonçalo (Sousa)');
    Cidade.create!(:estado_id => 15, :chave => '5080', :nome => 'São João Bosco (Uiraúna)');
    Cidade.create!(:estado_id => 15, :chave => '5081', :nome => 'São João do Cariri');
    Cidade.create!(:estado_id => 15, :chave => '5082', :nome => 'São João do Rio do Peixe');
    Cidade.create!(:estado_id => 15, :chave => '5083', :nome => 'São João do Tigre');
    Cidade.create!(:estado_id => 15, :chave => '5084', :nome => 'São José da Lagoa Tapada');
    Cidade.create!(:estado_id => 15, :chave => '5085', :nome => 'São José da Mata (Campina Grande)');
    Cidade.create!(:estado_id => 15, :chave => '5086', :nome => 'São José de Caiana');
    Cidade.create!(:estado_id => 15, :chave => '5087', :nome => 'São José de Espinharas');
    Cidade.create!(:estado_id => 15, :chave => '5088', :nome => 'São José de Marimbas (Cachoeira dos Índios)');
    Cidade.create!(:estado_id => 15, :chave => '5089', :nome => 'São José de Piranhas');
    Cidade.create!(:estado_id => 15, :chave => '5090', :nome => 'São José de Princesa');
    Cidade.create!(:estado_id => 15, :chave => '5091', :nome => 'São José do Bonfim');
    Cidade.create!(:estado_id => 15, :chave => '5092', :nome => 'São José do Brejo do Cruz');
    Cidade.create!(:estado_id => 15, :chave => '5093', :nome => 'São José do Sabugi');
    Cidade.create!(:estado_id => 15, :chave => '5094', :nome => 'São José dos Cordeiros');
    Cidade.create!(:estado_id => 15, :chave => '5095', :nome => 'São José dos Ramos');
    Cidade.create!(:estado_id => 15, :chave => '5096', :nome => 'São Mamede');
    Cidade.create!(:estado_id => 15, :chave => '5097', :nome => 'São Miguel de Taipu');
    Cidade.create!(:estado_id => 15, :chave => '5098', :nome => 'São Pedro (Santa Cruz)');
    Cidade.create!(:estado_id => 15, :chave => '5099', :nome => 'São Sebastião de Lagoa de Roça');
    Cidade.create!(:estado_id => 15, :chave => '5100', :nome => 'São Sebastião do Umbuzeiro');
    Cidade.create!(:estado_id => 15, :chave => '5101', :nome => 'Sapé');
    Cidade.create!(:estado_id => 15, :chave => '5102', :nome => 'Seridó (São Vicente do Seridó)');
    Cidade.create!(:estado_id => 15, :chave => '5103', :nome => 'São Vicente do Seridó');
    Cidade.create!(:estado_id => 15, :chave => '5104', :nome => 'Serra Branca');
    Cidade.create!(:estado_id => 15, :chave => '5105', :nome => 'Serra da Raiz');
    Cidade.create!(:estado_id => 15, :chave => '5106', :nome => 'Serra Grande');
    Cidade.create!(:estado_id => 15, :chave => '5107', :nome => 'Serra Redonda');
    Cidade.create!(:estado_id => 15, :chave => '5108', :nome => 'Serraria');
    Cidade.create!(:estado_id => 15, :chave => '5109', :nome => 'Sertãozinho');
    Cidade.create!(:estado_id => 15, :chave => '5110', :nome => 'Sobrado');
    Cidade.create!(:estado_id => 15, :chave => '5111', :nome => 'Solãnea');
    Cidade.create!(:estado_id => 15, :chave => '5112', :nome => 'Soledade');
    Cidade.create!(:estado_id => 15, :chave => '5113', :nome => 'Sossego');
    Cidade.create!(:estado_id => 15, :chave => '5114', :nome => 'Sousa');
    Cidade.create!(:estado_id => 15, :chave => '5115', :nome => 'Sucuru (Serra Branca)');
    Cidade.create!(:estado_id => 15, :chave => '5116', :nome => 'Sumé');
    Cidade.create!(:estado_id => 15, :chave => '5117', :nome => 'Campo de Santana');
    Cidade.create!(:estado_id => 15, :chave => '5119', :nome => 'Tambauzinho (Santa Rita)');
    Cidade.create!(:estado_id => 15, :chave => '5120', :nome => 'Taperoç');
    Cidade.create!(:estado_id => 15, :chave => '5121', :nome => 'Tavares');
    Cidade.create!(:estado_id => 15, :chave => '5122', :nome => 'Teixeira');
    Cidade.create!(:estado_id => 15, :chave => '5123', :nome => 'Tenório');
    Cidade.create!(:estado_id => 15, :chave => '5124', :nome => 'Triunfo');
    Cidade.create!(:estado_id => 15, :chave => '5125', :nome => 'Uiraúna');
    Cidade.create!(:estado_id => 15, :chave => '5126', :nome => 'Umari (São João do Rio do Peixe)');
    Cidade.create!(:estado_id => 15, :chave => '5127', :nome => 'Umbuzeiro');
    Cidade.create!(:estado_id => 15, :chave => '5128', :nome => 'Vçrzea');
    Cidade.create!(:estado_id => 15, :chave => '5129', :nome => 'Várzea Comprida (Pombal)');
    Cidade.create!(:estado_id => 15, :chave => '5130', :nome => 'Várzea Nova (Santa Rita)');
    Cidade.create!(:estado_id => 15, :chave => '5131', :nome => 'Vazante (Diamante)');
    Cidade.create!(:estado_id => 15, :chave => '5132', :nome => 'Vieirópolis');
    Cidade.create!(:estado_id => 15, :chave => '5133', :nome => 'Vista Serrana');
    Cidade.create!(:estado_id => 15, :chave => '5134', :nome => 'Zabelí');

  end

  def down
    Cidade.destroy_all
  end
end
