#!/bin/env ruby
# encoding: utf-8

class AddInitialBairro < ActiveRecord::Migration
  def up
    Bairro.create!( :chave => 41032, :cidade_id => Cidade.find_by_chave(4848).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41602, :cidade_id => Cidade.find_by_chave(4848).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 40864, :cidade_id => Cidade.find_by_chave(4849).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40666, :cidade_id => Cidade.find_by_chave(4850).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 41738, :cidade_id => Cidade.find_by_chave(4850).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40748, :cidade_id => Cidade.find_by_chave(4851).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41040, :cidade_id => Cidade.find_by_chave(4852).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41037, :cidade_id => Cidade.find_by_chave(4853).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41598, :cidade_id => Cidade.find_by_chave(4853).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 41275, :cidade_id => Cidade.find_by_chave(4854).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40860, :cidade_id => Cidade.find_by_chave(4855).id, :nome => 'Centro' )
    Bairro.create!( :chave => 43033, :cidade_id => Cidade.find_by_chave(4855).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 41183, :cidade_id => Cidade.find_by_chave(4856).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40761, :cidade_id => Cidade.find_by_chave(4857).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40972, :cidade_id => Cidade.find_by_chave(4858).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41582, :cidade_id => Cidade.find_by_chave(4858).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 40997, :cidade_id => Cidade.find_by_chave(4859).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40999, :cidade_id => Cidade.find_by_chave(4860).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40679, :cidade_id => Cidade.find_by_chave(4861).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41659, :cidade_id => Cidade.find_by_chave(4861).id, :nome => 'Povoado Cepilho' )
    Bairro.create!( :chave => 43471, :cidade_id => Cidade.find_by_chave(4861).id, :nome => 'Usina Santa Maria' )
    Bairro.create!( :chave => 41258, :cidade_id => Cidade.find_by_chave(4862).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40959, :cidade_id => Cidade.find_by_chave(4863).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40960, :cidade_id => Cidade.find_by_chave(4865).id, :nome => 'Centro' )
    Bairro.create!( :chave => 43050, :cidade_id => Cidade.find_by_chave(4866).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41180, :cidade_id => Cidade.find_by_chave(4867).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40690, :cidade_id => Cidade.find_by_chave(4868).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40684, :cidade_id => Cidade.find_by_chave(4870).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 42081, :cidade_id => Cidade.find_by_chave(4870).id, :nome => 'Centro' )
    Bairro.create!( :chave => 49050, :cidade_id => Cidade.find_by_chave(4870).id, :nome => 'Distritos' )
    Bairro.create!( :chave => 41160, :cidade_id => Cidade.find_by_chave(4871).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41000, :cidade_id => Cidade.find_by_chave(4872).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41230, :cidade_id => Cidade.find_by_chave(4873).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 41624, :cidade_id => Cidade.find_by_chave(4873).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40961, :cidade_id => Cidade.find_by_chave(4874).id, :nome => 'Centro' )
    Bairro.create!( :chave => 45914, :cidade_id => Cidade.find_by_chave(4875).id, :nome => 'Centro' )
    Bairro.create!( :chave => 6928, :cidade_id => Cidade.find_by_chave(4876).id, :nome => 'Aeroporto' )
    Bairro.create!( :chave => 6929, :cidade_id => Cidade.find_by_chave(4876).id, :nome => 'Alto da Boa Vista' )
    Bairro.create!( :chave => 6930, :cidade_id => Cidade.find_by_chave(4876).id, :nome => 'Baralho' )
    Bairro.create!( :chave => 6931, :cidade_id => Cidade.find_by_chave(4876).id, :nome => 'BrasÌlia' )
    Bairro.create!( :chave => 6932, :cidade_id => Cidade.find_by_chave(4876).id, :nome => 'Centro' )
    Bairro.create!( :chave => 6933, :cidade_id => Cidade.find_by_chave(4876).id, :nome => 'Imaculada' )
    Bairro.create!( :chave => 6934, :cidade_id => Cidade.find_by_chave(4876).id, :nome => 'Jardim S„o Severino' )
    Bairro.create!( :chave => 6935, :cidade_id => Cidade.find_by_chave(4876).id, :nome => 'Manguinhos' )
    Bairro.create!( :chave => 6936, :cidade_id => Cidade.find_by_chave(4876).id, :nome => 'Mutir„o' )
    Bairro.create!( :chave => 6937, :cidade_id => Cidade.find_by_chave(4876).id, :nome => 'Rio do Meio' )
    Bairro.create!( :chave => 6938, :cidade_id => Cidade.find_by_chave(4876).id, :nome => 'S„o Bento' )
    Bairro.create!( :chave => 6940, :cidade_id => Cidade.find_by_chave(4876).id, :nome => 'Sesi' )
    Bairro.create!( :chave => 6941, :cidade_id => Cidade.find_by_chave(4876).id, :nome => 'Tambay' )
    Bairro.create!( :chave => 41012, :cidade_id => Cidade.find_by_chave(4877).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41581, :cidade_id => Cidade.find_by_chave(4877).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 41588, :cidade_id => Cidade.find_by_chave(4877).id, :nome => 'Sitio' )
    Bairro.create!( :chave => 41096, :cidade_id => Cidade.find_by_chave(4878).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41228, :cidade_id => Cidade.find_by_chave(4879).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41042, :cidade_id => Cidade.find_by_chave(4880).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40967, :cidade_id => Cidade.find_by_chave(4881).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41070, :cidade_id => Cidade.find_by_chave(4882).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41097, :cidade_id => Cidade.find_by_chave(4883).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41281, :cidade_id => Cidade.find_by_chave(4884).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41098, :cidade_id => Cidade.find_by_chave(4885).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41580, :cidade_id => Cidade.find_by_chave(4885).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 40963, :cidade_id => Cidade.find_by_chave(4886).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41583, :cidade_id => Cidade.find_by_chave(4886).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 41014, :cidade_id => Cidade.find_by_chave(4887).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41099, :cidade_id => Cidade.find_by_chave(4888).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40744, :cidade_id => Cidade.find_by_chave(4889).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40673, :cidade_id => Cidade.find_by_chave(4890).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 42252, :cidade_id => Cidade.find_by_chave(4890).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40964, :cidade_id => Cidade.find_by_chave(4891).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40971, :cidade_id => Cidade.find_by_chave(4892).id, :nome => 'Centro' )
    Bairro.create!( :chave => 42088, :cidade_id => Cidade.find_by_chave(4892).id, :nome => 'Intermares' )
    Bairro.create!( :chave => 41282, :cidade_id => Cidade.find_by_chave(4893).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41100, :cidade_id => Cidade.find_by_chave(4894).id, :nome => 'Distrito' )
    Bairro.create!( :chave => 41671, :cidade_id => Cidade.find_by_chave(4894).id, :nome => 'Centro' )
    Bairro.create!( :chave => 43022, :cidade_id => Cidade.find_by_chave(4894).id, :nome => 'Distrito de F·tima' )
    Bairro.create!( :chave => 41133, :cidade_id => Cidade.find_by_chave(4896).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41004, :cidade_id => Cidade.find_by_chave(4897).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41221, :cidade_id => Cidade.find_by_chave(4898).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41006, :cidade_id => Cidade.find_by_chave(4899).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40998, :cidade_id => Cidade.find_by_chave(4900).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41164, :cidade_id => Cidade.find_by_chave(4901).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40880, :cidade_id => Cidade.find_by_chave(4902).id, :nome => 'Centro' )
    Bairro.create!( :chave => 49055, :cidade_id => Cidade.find_by_chave(4902).id, :nome => 'Povoado de Caj·' )
    Bairro.create!( :chave => 40965, :cidade_id => Cidade.find_by_chave(4903).id, :nome => 'Centro' )
    Bairro.create!( :chave => 6942, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Alto Branco' )
    Bairro.create!( :chave => 6943, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Bela Vista' )
    Bairro.create!( :chave => 6944, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'BodocongÛ' )
    Bairro.create!( :chave => 6945, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Catingueira' )
    Bairro.create!( :chave => 6946, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'CatolÈ' )
    Bairro.create!( :chave => 6947, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Centen·rio' )
    Bairro.create!( :chave => 6948, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Centro' )
    Bairro.create!( :chave => 6949, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Cidades' )
    Bairro.create!( :chave => 6950, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'ConceiÁ„o' )
    Bairro.create!( :chave => 6951, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Cruzeiro' )
    Bairro.create!( :chave => 6952, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Distrito Industrial' )
    Bairro.create!( :chave => 6953, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Jardim Paulistano' )
    Bairro.create!( :chave => 6954, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Jardim Quarenta' )
    Bairro.create!( :chave => 6955, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Jeremias' )
    Bairro.create!( :chave => 6956, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'JosÈ Pinheiro' )
    Bairro.create!( :chave => 6957, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Liberdade' )
    Bairro.create!( :chave => 6958, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Mirante' )
    Bairro.create!( :chave => 6959, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Monte Castelo' )
    Bairro.create!( :chave => 6960, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Monte Santo' )
    Bairro.create!( :chave => 6961, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'NaÁıes' )
    Bairro.create!( :chave => 6962, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Nova BrasÌlia' )
    Bairro.create!( :chave => 6963, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Palmeira' )
    Bairro.create!( :chave => 6964, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Prata' )
    Bairro.create!( :chave => 6965, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Santa Rosa' )
    Bairro.create!( :chave => 6966, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Santo AntÙnio' )
    Bairro.create!( :chave => 6967, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'S„o JosÈ' )
    Bairro.create!( :chave => 6968, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Tambor' )
    Bairro.create!( :chave => 6969, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'Vila Cabral' )
    Bairro.create!( :chave => 35335, :cidade_id => Cidade.find_by_chave(4904).id, :nome => 'CuitÈs' )
    Bairro.create!( :chave => 41280, :cidade_id => Cidade.find_by_chave(4906).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41652, :cidade_id => Cidade.find_by_chave(4907).id, :nome => 'SÌtio' )
    Bairro.create!( :chave => 41181, :cidade_id => Cidade.find_by_chave(4908).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41022, :cidade_id => Cidade.find_by_chave(4909).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41672, :cidade_id => Cidade.find_by_chave(4909).id, :nome => 'Povoado de Barreiras' )
    Bairro.create!( :chave => 41406, :cidade_id => Cidade.find_by_chave(4910).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41060, :cidade_id => Cidade.find_by_chave(4911).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41172, :cidade_id => Cidade.find_by_chave(4912).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41273, :cidade_id => Cidade.find_by_chave(4913).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41002, :cidade_id => Cidade.find_by_chave(4914).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41287, :cidade_id => Cidade.find_by_chave(4915).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40969, :cidade_id => Cidade.find_by_chave(4916).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41257, :cidade_id => Cidade.find_by_chave(4917).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41402, :cidade_id => Cidade.find_by_chave(4918).id, :nome => 'Centro' )
    Bairro.create!( :chave => 43462, :cidade_id => Cidade.find_by_chave(4918).id, :nome => 'Povoado Cepilho' )
    Bairro.create!( :chave => 41005, :cidade_id => Cidade.find_by_chave(4919).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41101, :cidade_id => Cidade.find_by_chave(4920).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40657, :cidade_id => Cidade.find_by_chave(4921).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41151, :cidade_id => Cidade.find_by_chave(4922).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40956, :cidade_id => Cidade.find_by_chave(4923).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41408, :cidade_id => Cidade.find_by_chave(4924).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41179, :cidade_id => Cidade.find_by_chave(4925).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40670, :cidade_id => Cidade.find_by_chave(4926).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41153, :cidade_id => Cidade.find_by_chave(4927).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41011, :cidade_id => Cidade.find_by_chave(4928).id, :nome => 'Centro' )
    Bairro.create!( :chave => 43472, :cidade_id => Cidade.find_by_chave(4928).id, :nome => 'Distrito de Melo' )
    Bairro.create!( :chave => 40686, :cidade_id => Cidade.find_by_chave(4929).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41007, :cidade_id => Cidade.find_by_chave(4930).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40688, :cidade_id => Cidade.find_by_chave(4932).id, :nome => 'Centro' )
    Bairro.create!( :chave => 43352, :cidade_id => Cidade.find_by_chave(4932).id, :nome => 'Povoado Estacada' )
    Bairro.create!( :chave => 41038, :cidade_id => Cidade.find_by_chave(4933).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41173, :cidade_id => Cidade.find_by_chave(4934).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41074, :cidade_id => Cidade.find_by_chave(4935).id, :nome => 'Centro' )
    Bairro.create!( :chave => 43353, :cidade_id => Cidade.find_by_chave(4935).id, :nome => 'Povoado de Tataira' )
    Bairro.create!( :chave => 41109, :cidade_id => Cidade.find_by_chave(4936).id, :nome => 'Centro' )
    Bairro.create!( :chave => 43460, :cidade_id => Cidade.find_by_chave(4936).id, :nome => 'Distrito de Vazante' )
    Bairro.create!( :chave => 41008, :cidade_id => Cidade.find_by_chave(4937).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41009, :cidade_id => Cidade.find_by_chave(4938).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41110, :cidade_id => Cidade.find_by_chave(4939).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41167, :cidade_id => Cidade.find_by_chave(4940).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41152, :cidade_id => Cidade.find_by_chave(4941).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41041, :cidade_id => Cidade.find_by_chave(4942).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41276, :cidade_id => Cidade.find_by_chave(4943).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41010, :cidade_id => Cidade.find_by_chave(4946).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41253, :cidade_id => Cidade.find_by_chave(4947).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41013, :cidade_id => Cidade.find_by_chave(4948).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40953, :cidade_id => Cidade.find_by_chave(4949).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 42082, :cidade_id => Cidade.find_by_chave(4949).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40954, :cidade_id => Cidade.find_by_chave(4951).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41043, :cidade_id => Cidade.find_by_chave(4952).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41135, :cidade_id => Cidade.find_by_chave(4953).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41033, :cidade_id => Cidade.find_by_chave(4954).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41106, :cidade_id => Cidade.find_by_chave(4955).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41044, :cidade_id => Cidade.find_by_chave(4956).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40957, :cidade_id => Cidade.find_by_chave(4957).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40958, :cidade_id => Cidade.find_by_chave(4959).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40667, :cidade_id => Cidade.find_by_chave(4960).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41047, :cidade_id => Cidade.find_by_chave(4961).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40676, :cidade_id => Cidade.find_by_chave(4962).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41591, :cidade_id => Cidade.find_by_chave(4962).id, :nome => 'Sitio' )
    Bairro.create!( :chave => 41593, :cidade_id => Cidade.find_by_chave(4962).id, :nome => 'Distrito' )
    Bairro.create!( :chave => 41103, :cidade_id => Cidade.find_by_chave(4963).id, :nome => 'Centro' )
    Bairro.create!( :chave => 6970, :cidade_id => Cidade.find_by_chave(4964).id, :nome => '¡gua Fria' )
    Bairro.create!( :chave => 6971, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Altiplano Cabo Branco' )
    Bairro.create!( :chave => 6972, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Alto do Mateus' )
    Bairro.create!( :chave => 6973, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Bessa' )
    Bairro.create!( :chave => 6974, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Brisamar' )
    Bairro.create!( :chave => 6975, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Cabo Branco' )
    Bairro.create!( :chave => 6976, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Castelo Branco' )
    Bairro.create!( :chave => 6977, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Centro' )
    Bairro.create!( :chave => 6978, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Funcion·rios' )
    Bairro.create!( :chave => 6979, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Trincheiras' )
    Bairro.create!( :chave => 6980, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Costa e Silva' )
    Bairro.create!( :chave => 6981, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Cristo Redentor' )
    Bairro.create!( :chave => 6982, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Cruz das Armas' )
    Bairro.create!( :chave => 6983, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Distrito Industrial' )
    Bairro.create!( :chave => 6984, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Ernani S·tiro' )
    Bairro.create!( :chave => 6985, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Ernesto Geisel' )
    Bairro.create!( :chave => 6986, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Estados' )
    Bairro.create!( :chave => 6987, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Expedicion·rios' )
    Bairro.create!( :chave => 6988, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Funcion·rios II' )
    Bairro.create!( :chave => 6989, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Ilha do Bispo' )
    Bairro.create!( :chave => 6990, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Ind˙strias' )
    Bairro.create!( :chave => 6991, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'IpÍs' )
    Bairro.create!( :chave => 6992, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Jaguaribe' )
    Bairro.create!( :chave => 6993, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Jardim Cidade Universit·ria' )
    Bairro.create!( :chave => 6996, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Jardim Planalto' )
    Bairro.create!( :chave => 6997, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Jardim Veneza' )
    Bairro.create!( :chave => 6998, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'JosÈ AmÈrico de Almeida' )
    Bairro.create!( :chave => 6999, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'ManaÌra' )
    Bairro.create!( :chave => 7000, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Mandacaru' )
    Bairro.create!( :chave => 7001, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Mangabeira' )
    Bairro.create!( :chave => 7002, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'MarÈs' )
    Bairro.create!( :chave => 7003, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Miramar' )
    Bairro.create!( :chave => 7004, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Novais' )
    Bairro.create!( :chave => 7005, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Rangel' )
    Bairro.create!( :chave => 7006, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Roger' )
    Bairro.create!( :chave => 7007, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'S„o JosÈ' )
    Bairro.create!( :chave => 7008, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Ponta do Seixas' )
    Bairro.create!( :chave => 7009, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Tamba˙' )
    Bairro.create!( :chave => 7010, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Tambauzinho' )
    Bairro.create!( :chave => 7011, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Tambi·' )
    Bairro.create!( :chave => 7012, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Torre' )
    Bairro.create!( :chave => 7013, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Treze de Maio' )
    Bairro.create!( :chave => 7014, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Valentina de Figueiredo' )
    Bairro.create!( :chave => 7015, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Varadouro' )
    Bairro.create!( :chave => 37491, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Portal do Sol' )
    Bairro.create!( :chave => 37500, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'MuÁumagro' )
    Bairro.create!( :chave => 37531, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Jardim das Ac·cias' )
    Bairro.create!( :chave => 37627, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Jardim S„o Paulo' )
    Bairro.create!( :chave => 37650, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'AnatÛlia' )
    Bairro.create!( :chave => 37729, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Banc·rios' )
    Bairro.create!( :chave => 37952, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Cidade dos Colibris' )
    Bairro.create!( :chave => 37960, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Cui·' )
    Bairro.create!( :chave => 37964, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Jo„o Paulo II' )
    Bairro.create!( :chave => 43475, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Aeroclube' )
    Bairro.create!( :chave => 43481, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Gramame' )
    Bairro.create!( :chave => 43490, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Pedro Gondim' )
    Bairro.create!( :chave => 43494, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Jo„o Agripino' )
    Bairro.create!( :chave => 43523, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Paratibe' )
    Bairro.create!( :chave => 43587, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Jardim Oceania' )
    Bairro.create!( :chave => 43590, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Padre ZÈ' )
    Bairro.create!( :chave => 43669, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Penha' )
    Bairro.create!( :chave => 49509, :cidade_id => Cidade.find_by_chave(4964).id, :nome => 'Planalto Boa EsperanÁa' )
    Bairro.create!( :chave => 41048, :cidade_id => Cidade.find_by_chave(4965).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 43035, :cidade_id => Cidade.find_by_chave(4965).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41137, :cidade_id => Cidade.find_by_chave(4966).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 43179, :cidade_id => Cidade.find_by_chave(4966).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41138, :cidade_id => Cidade.find_by_chave(4967).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41609, :cidade_id => Cidade.find_by_chave(4967).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 40681, :cidade_id => Cidade.find_by_chave(4968).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41139, :cidade_id => Cidade.find_by_chave(4969).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41104, :cidade_id => Cidade.find_by_chave(4970).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41001, :cidade_id => Cidade.find_by_chave(4971).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41259, :cidade_id => Cidade.find_by_chave(4972).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41049, :cidade_id => Cidade.find_by_chave(4973).id, :nome => 'Povoado Ch„ do Marinho' )
    Bairro.create!( :chave => 41579, :cidade_id => Cidade.find_by_chave(4973).id, :nome => 'SÌtio' )
    Bairro.create!( :chave => 41660, :cidade_id => Cidade.find_by_chave(4973).id, :nome => 'Centro' )
    Bairro.create!( :chave => 43468, :cidade_id => Cidade.find_by_chave(4973).id, :nome => 'Povoado Floriano' )
    Bairro.create!( :chave => 43469, :cidade_id => Cidade.find_by_chave(4973).id, :nome => 'Povoado S„o Pedro' )
    Bairro.create!( :chave => 41069, :cidade_id => Cidade.find_by_chave(4974).id, :nome => 'Centro' )
    Bairro.create!( :chave => 43439, :cidade_id => Cidade.find_by_chave(4975).id, :nome => 'Centro' )
    Bairro.create!( :chave => 43461, :cidade_id => Cidade.find_by_chave(4975).id, :nome => 'Povoado de Lerol‚ndia' )
    Bairro.create!( :chave => 41143, :cidade_id => Cidade.find_by_chave(4976).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41270, :cidade_id => Cidade.find_by_chave(4977).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40683, :cidade_id => Cidade.find_by_chave(4978).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41150, :cidade_id => Cidade.find_by_chave(4979).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41289, :cidade_id => Cidade.find_by_chave(4980).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41149, :cidade_id => Cidade.find_by_chave(4981).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41036, :cidade_id => Cidade.find_by_chave(4982).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41584, :cidade_id => Cidade.find_by_chave(4982).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 41148, :cidade_id => Cidade.find_by_chave(4983).id, :nome => 'Centro' )
    Bairro.create!( :chave => 49049, :cidade_id => Cidade.find_by_chave(4983).id, :nome => 'Distritos' )
    Bairro.create!( :chave => 40867, :cidade_id => Cidade.find_by_chave(4984).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40743, :cidade_id => Cidade.find_by_chave(4985).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40760, :cidade_id => Cidade.find_by_chave(4986).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41050, :cidade_id => Cidade.find_by_chave(4987).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41222, :cidade_id => Cidade.find_by_chave(4988).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41290, :cidade_id => Cidade.find_by_chave(4989).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40691, :cidade_id => Cidade.find_by_chave(4990).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41269, :cidade_id => Cidade.find_by_chave(4991).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41185, :cidade_id => Cidade.find_by_chave(4992).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41094, :cidade_id => Cidade.find_by_chave(4993).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40739, :cidade_id => Cidade.find_by_chave(4995).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40862, :cidade_id => Cidade.find_by_chave(4996).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40968, :cidade_id => Cidade.find_by_chave(4997).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41045, :cidade_id => Cidade.find_by_chave(4998).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41590, :cidade_id => Cidade.find_by_chave(4998).id, :nome => 'Sitio' )
    Bairro.create!( :chave => 41407, :cidade_id => Cidade.find_by_chave(4999).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40946, :cidade_id => Cidade.find_by_chave(5000).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41291, :cidade_id => Cidade.find_by_chave(5001).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41026, :cidade_id => Cidade.find_by_chave(5002).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41288, :cidade_id => Cidade.find_by_chave(5003).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40879, :cidade_id => Cidade.find_by_chave(5004).id, :nome => 'Centro' )
    Bairro.create!( :chave => 43440, :cidade_id => Cidade.find_by_chave(5005).id, :nome => 'Centro' )
    Bairro.create!( :chave => 43458, :cidade_id => Cidade.find_by_chave(5005).id, :nome => 'Distrito de Nossa Senhora do Livramento' )
    Bairro.create!( :chave => 40947, :cidade_id => Cidade.find_by_chave(5006).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41147, :cidade_id => Cidade.find_by_chave(5007).id, :nome => 'Centro' )
    Bairro.create!( :chave => 49051, :cidade_id => Cidade.find_by_chave(5007).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 41016, :cidade_id => Cidade.find_by_chave(5008).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41409, :cidade_id => Cidade.find_by_chave(5009).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41410, :cidade_id => Cidade.find_by_chave(5010).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41146, :cidade_id => Cidade.find_by_chave(5012).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40703, :cidade_id => Cidade.find_by_chave(5013).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41039, :cidade_id => Cidade.find_by_chave(5014).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41165, :cidade_id => Cidade.find_by_chave(5015).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41140, :cidade_id => Cidade.find_by_chave(5016).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41622, :cidade_id => Cidade.find_by_chave(5016).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 7016, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'Belo Horizonte' )
    Bairro.create!( :chave => 7017, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'BrasÌlia' )
    Bairro.create!( :chave => 7018, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'Centro' )
    Bairro.create!( :chave => 7019, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'Conjunto Bivar Olinto' )
    Bairro.create!( :chave => 7020, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'Conjunto NoÈ Trajano' )
    Bairro.create!( :chave => 7023, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'Jardim Bela Vista' )
    Bairro.create!( :chave => 7025, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'Jardim CalifÛrnia' )
    Bairro.create!( :chave => 7027, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'Jardim Europa' )
    Bairro.create!( :chave => 7028, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'Jardim Guanabara' )
    Bairro.create!( :chave => 7029, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'Jardim Lacerda' )
    Bairro.create!( :chave => 7030, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'Jardim MagnÛlia' )
    Bairro.create!( :chave => 7033, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'Jardim Queiroz' )
    Bairro.create!( :chave => 7036, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'Jatob·' )
    Bairro.create!( :chave => 7037, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'Ju· Doce' )
    Bairro.create!( :chave => 7038, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'Liberdade' )
    Bairro.create!( :chave => 7039, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'Maternidade' )
    Bairro.create!( :chave => 7040, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'Monte Castelo' )
    Bairro.create!( :chave => 7041, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'Morro' )
    Bairro.create!( :chave => 7042, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'Salgadinho' )
    Bairro.create!( :chave => 7043, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'Santa CecÌlia' )
    Bairro.create!( :chave => 7044, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'Santo AntÙnio' )
    Bairro.create!( :chave => 7045, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'S„o Sebasti„o' )
    Bairro.create!( :chave => 7046, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'Vila Cavalcante' )
    Bairro.create!( :chave => 7047, :cidade_id => Cidade.find_by_chave(5017).id, :nome => 'VitÛria' )
    Bairro.create!( :chave => 40875, :cidade_id => Cidade.find_by_chave(5018).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41141, :cidade_id => Cidade.find_by_chave(5019).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41028, :cidade_id => Cidade.find_by_chave(5020).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40857, :cidade_id => Cidade.find_by_chave(5021).id, :nome => 'Centro' )
    Bairro.create!( :chave => 49052, :cidade_id => Cidade.find_by_chave(5021).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 41226, :cidade_id => Cidade.find_by_chave(5022).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41020, :cidade_id => Cidade.find_by_chave(5025).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41021, :cidade_id => Cidade.find_by_chave(5026).id, :nome => 'Centro' )
    Bairro.create!( :chave => 42038, :cidade_id => Cidade.find_by_chave(5026).id, :nome => 'SÌtio' )
    Bairro.create!( :chave => 42043, :cidade_id => Cidade.find_by_chave(5026).id, :nome => 'Povoado Santa Luzia' )
    Bairro.create!( :chave => 40753, :cidade_id => Cidade.find_by_chave(5027).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40948, :cidade_id => Cidade.find_by_chave(5028).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40949, :cidade_id => Cidade.find_by_chave(5029).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41400, :cidade_id => Cidade.find_by_chave(5030).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41401, :cidade_id => Cidade.find_by_chave(5031).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40950, :cidade_id => Cidade.find_by_chave(5033).id, :nome => 'Centro' )
    Bairro.create!( :chave => 45913, :cidade_id => Cidade.find_by_chave(5034).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41003, :cidade_id => Cidade.find_by_chave(5035).id, :nome => 'Centro' )
    Bairro.create!( :chave => 43351, :cidade_id => Cidade.find_by_chave(5035).id, :nome => 'Povoado Nova Vida' )
    Bairro.create!( :chave => 41025, :cidade_id => Cidade.find_by_chave(5036).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 42048, :cidade_id => Cidade.find_by_chave(5036).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41174, :cidade_id => Cidade.find_by_chave(5037).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41254, :cidade_id => Cidade.find_by_chave(5038).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41027, :cidade_id => Cidade.find_by_chave(5039).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41030, :cidade_id => Cidade.find_by_chave(5041).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41031, :cidade_id => Cidade.find_by_chave(5042).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41017, :cidade_id => Cidade.find_by_chave(5043).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 41663, :cidade_id => Cidade.find_by_chave(5043).id, :nome => 'SÌtio' )
    Bairro.create!( :chave => 41668, :cidade_id => Cidade.find_by_chave(5043).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41018, :cidade_id => Cidade.find_by_chave(5044).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41592, :cidade_id => Cidade.find_by_chave(5044).id, :nome => 'Sitio' )
    Bairro.create!( :chave => 41229, :cidade_id => Cidade.find_by_chave(5045).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40951, :cidade_id => Cidade.find_by_chave(5047).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41658, :cidade_id => Cidade.find_by_chave(5047).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 41267, :cidade_id => Cidade.find_by_chave(5048).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41161, :cidade_id => Cidade.find_by_chave(5049).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41255, :cidade_id => Cidade.find_by_chave(5050).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40873, :cidade_id => Cidade.find_by_chave(5051).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41034, :cidade_id => Cidade.find_by_chave(5053).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41585, :cidade_id => Cidade.find_by_chave(5053).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 41251, :cidade_id => Cidade.find_by_chave(5054).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41286, :cidade_id => Cidade.find_by_chave(5055).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41072, :cidade_id => Cidade.find_by_chave(5056).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40970, :cidade_id => Cidade.find_by_chave(5057).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 45912, :cidade_id => Cidade.find_by_chave(5057).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41231, :cidade_id => Cidade.find_by_chave(5058).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40872, :cidade_id => Cidade.find_by_chave(5059).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41285, :cidade_id => Cidade.find_by_chave(5060).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40855, :cidade_id => Cidade.find_by_chave(5061).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41404, :cidade_id => Cidade.find_by_chave(5062).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41107, :cidade_id => Cidade.find_by_chave(5063).id, :nome => 'Centro' )
    Bairro.create!( :chave => 43056, :cidade_id => Cidade.find_by_chave(5064).id, :nome => 'Centro' )
    Bairro.create!( :chave => 7048, :cidade_id => Cidade.find_by_chave(5066).id, :nome => 'Centro' )
    Bairro.create!( :chave => 7049, :cidade_id => Cidade.find_by_chave(5066).id, :nome => 'Liberdade' )
    Bairro.create!( :chave => 7050, :cidade_id => Cidade.find_by_chave(5066).id, :nome => 'MunicÌpios' )
    Bairro.create!( :chave => 7051, :cidade_id => Cidade.find_by_chave(5066).id, :nome => 'Popular' )
    Bairro.create!( :chave => 7052, :cidade_id => Cidade.find_by_chave(5066).id, :nome => 'Vila Tibiri' )
    Bairro.create!( :chave => 44133, :cidade_id => Cidade.find_by_chave(5066).id, :nome => 'Capit„o' )
    Bairro.create!( :chave => 41075, :cidade_id => Cidade.find_by_chave(5068).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41073, :cidade_id => Cidade.find_by_chave(5070).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41092, :cidade_id => Cidade.find_by_chave(5071).id, :nome => 'Centro' )
    Bairro.create!( :chave => 49048, :cidade_id => Cidade.find_by_chave(5071).id, :nome => 'Distritos' )
    Bairro.create!( :chave => 41227, :cidade_id => Cidade.find_by_chave(5072).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41252, :cidade_id => Cidade.find_by_chave(5073).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40854, :cidade_id => Cidade.find_by_chave(5074).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41403, :cidade_id => Cidade.find_by_chave(5075).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41168, :cidade_id => Cidade.find_by_chave(5076).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41163, :cidade_id => Cidade.find_by_chave(5077).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41182, :cidade_id => Cidade.find_by_chave(5078).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41284, :cidade_id => Cidade.find_by_chave(5079).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41019, :cidade_id => Cidade.find_by_chave(5081).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40669, :cidade_id => Cidade.find_by_chave(5082).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41023, :cidade_id => Cidade.find_by_chave(5083).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40763, :cidade_id => Cidade.find_by_chave(5084).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41277, :cidade_id => Cidade.find_by_chave(5085).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40762, :cidade_id => Cidade.find_by_chave(5086).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41134, :cidade_id => Cidade.find_by_chave(5087).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41178, :cidade_id => Cidade.find_by_chave(5088).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40962, :cidade_id => Cidade.find_by_chave(5089).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41274, :cidade_id => Cidade.find_by_chave(5090).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41088, :cidade_id => Cidade.find_by_chave(5091).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41166, :cidade_id => Cidade.find_by_chave(5092).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41089, :cidade_id => Cidade.find_by_chave(5093).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41035, :cidade_id => Cidade.find_by_chave(5094).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41186, :cidade_id => Cidade.find_by_chave(5095).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41105, :cidade_id => Cidade.find_by_chave(5096).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40945, :cidade_id => Cidade.find_by_chave(5097).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41169, :cidade_id => Cidade.find_by_chave(5098).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41024, :cidade_id => Cidade.find_by_chave(5099).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41015, :cidade_id => Cidade.find_by_chave(5100).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41144, :cidade_id => Cidade.find_by_chave(5101).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41224, :cidade_id => Cidade.find_by_chave(5102).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41029, :cidade_id => Cidade.find_by_chave(5103).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41076, :cidade_id => Cidade.find_by_chave(5104).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40952, :cidade_id => Cidade.find_by_chave(5105).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40859, :cidade_id => Cidade.find_by_chave(5106).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41608, :cidade_id => Cidade.find_by_chave(5107).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41610, :cidade_id => Cidade.find_by_chave(5107).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 40892, :cidade_id => Cidade.find_by_chave(5108).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41272, :cidade_id => Cidade.find_by_chave(5109).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41268, :cidade_id => Cidade.find_by_chave(5110).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41046, :cidade_id => Cidade.find_by_chave(5111).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41136, :cidade_id => Cidade.find_by_chave(5112).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41271, :cidade_id => Cidade.find_by_chave(5113).id, :nome => 'Centro' )
    Bairro.create!( :chave => 7053, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'Alto Capanema' )
    Bairro.create!( :chave => 7054, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'Alto do Cruzeiro' )
    Bairro.create!( :chave => 7055, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'AndrÈ Gadelha' )
    Bairro.create!( :chave => 7056, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'Angelim' )
    Bairro.create!( :chave => 7057, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'Areia' )
    Bairro.create!( :chave => 7058, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'Bela Vista' )
    Bairro.create!( :chave => 7059, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'Centro' )
    Bairro.create!( :chave => 7060, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'EstaÁ„o' )
    Bairro.create!( :chave => 7061, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'Estreito' )
    Bairro.create!( :chave => 7062, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'Gato Preto' )
    Bairro.create!( :chave => 7063, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'Guanabara' )
    Bairro.create!( :chave => 7064, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'Jardim BrasÌlia' )
    Bairro.create!( :chave => 7065, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'Jardim DezirÈ' )
    Bairro.create!( :chave => 7066, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'Jardim Iracema' )
    Bairro.create!( :chave => 7067, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'Jardim Santana' )
    Bairro.create!( :chave => 7068, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'Jardim Sorril‚ndia' )
    Bairro.create!( :chave => 7069, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'Maria de Lourdes Sarmento Meira' )
    Bairro.create!( :chave => 7070, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'Mutir„o' )
    Bairro.create!( :chave => 7072, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'S„o JosÈ' )
    Bairro.create!( :chave => 7073, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'V·rzea da Cruz' )
    Bairro.create!( :chave => 44132, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'N˙cleo I' )
    Bairro.create!( :chave => 49194, :cidade_id => Cidade.find_by_chave(5114).id, :nome => 'Maria Raquel' )
    Bairro.create!( :chave => 41225, :cidade_id => Cidade.find_by_chave(5115).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41145, :cidade_id => Cidade.find_by_chave(5116).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40955, :cidade_id => Cidade.find_by_chave(5117).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41091, :cidade_id => Cidade.find_by_chave(5120).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41071, :cidade_id => Cidade.find_by_chave(5121).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41087, :cidade_id => Cidade.find_by_chave(5122).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41177, :cidade_id => Cidade.find_by_chave(5123).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40856, :cidade_id => Cidade.find_by_chave(5124).id, :nome => 'Centro' )
    Bairro.create!( :chave => 40881, :cidade_id => Cidade.find_by_chave(5125).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41405, :cidade_id => Cidade.find_by_chave(5126).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41120, :cidade_id => Cidade.find_by_chave(5127).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 41607, :cidade_id => Cidade.find_by_chave(5127).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41095, :cidade_id => Cidade.find_by_chave(5128).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41223, :cidade_id => Cidade.find_by_chave(5129).id, :nome => 'Centro' )
    Bairro.create!( :chave => 43066, :cidade_id => Cidade.find_by_chave(5130).id, :nome => 'Povoado' )
    Bairro.create!( :chave => 48594, :cidade_id => Cidade.find_by_chave(5131).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41176, :cidade_id => Cidade.find_by_chave(5132).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41108, :cidade_id => Cidade.find_by_chave(5133).id, :nome => 'Centro' )
    Bairro.create!( :chave => 41175, :cidade_id => Cidade.find_by_chave(5134).id, :nome => 'Centro' )

  end

  def down
    Bairro.destroy_all
  end
end
